%YAML 1.2
# realsense data loader settings
---
name: realsense_dataloader
type: ds3d::dataloader
out_caps: ds3d/datamap
custom_lib_path: libnvds_3d_dataloader_realsense.so
custom_create_function: createRealsenseDataloader
config_body:
  streams: [color, depth] # load color and depth only
  aligned_image_to_depth: False # default False

# point2cloud data filter settings
# convert depth and color into point-xyz data and pointUVcoordinates
---
name: point2cloud_datafilter
type: ds3d::datafilter
in_caps: ds3d/datamap
out_caps: ds3d/datamap
custom_lib_path: libnvds_3d_depth2point_datafilter.so
custom_create_function: createDepth2PointFilter
config_body:
  in_streams: [color, depth]
  max_points: 407040 # 848*480
  mem_pool_size: 8

# point cloud with color image data render settings
---
name: point-render
type: ds3d::datarender
in_caps: ds3d/datamap
custom_lib_path: libnvds_3d_gl_datarender.so
custom_create_function: createPointCloudDataRender
gst_properties:
  sync: False
  async: False
  drop: False
config_body:
  title: 3d-point-cloud-test
  streams: [points]
  width: 1280
  height: 720
  block: True
  view_position: [0, 0, -1] # view position in xyz coordinates
  view_target: [0, 0, 1] # view target which is the direction pointing to
  view_up: [0, -1.0, 0] # view up direction
  near: 0.01 # nearest points of perspective
  far: 10.0 # farmost points of perspective
  fov: 40.0 # FOV of perspective
  coord_y_opposite: False #UV(xy) coordination position of texture, realsense use same uv as gl texture
  positive_z_only: False

# for debug
---
  name: debugdump
  type: ds3d::userapp
  enable_debug: False
