%YAML 1.2
---
name: realsense_dataloader
type: ds3d::dataloader
out_caps: ds3d/datamap
custom_lib_path: libnvds_3d_dataloader_realsense.so
custom_create_function: createRealsenseDataloader
config_body:
  streams: [color, depth]
  framerate: 0

---
name: depth-render
type: ds3d::datarender
in_caps: ds3d/datamap
custom_lib_path: libnvds_3d_gl_datarender.so
custom_create_function: createDepthStreamDataRender
gst_properties:
  sync: False
  async: False
  drop: False
config_body:
  streams: [depth, color]
  width: 1920
  height: 544
  title: 3d-camera-app
  block: True
  # depth value out of [min_depth, max_depth] would be clamped.
  min_depth: 0.3 # in meters
  max_depth: 2.0 # in meters
  min_depth_color: [255, 128, 0] # RGB color value for minimum depth
  max_depth_color: [0, 128, 255] # RGB color value for maximum depth

---
  name: debugdump
  type: ds3d::userapp
  enable_debug: False
